package com.vosto.customer.services;

public enum ResultType {
	
	CREATE_CUSTOMER,
	AUTHENTICATE_CUSTOMER,
    UPDATE_CUSTOMER,
	RESET_PIN,
	GET_STORES,
	GET_TAGS,
	SEARCH_STORES,
	GET_PRODUCTS,
	GET_TAXONS,
	GET_VARIANTS,
	PLACE_ORDER,
	GET_PREVIOUS_ORDERS
}