package com.vosto.customer.services;

public enum ResultType {
	CREATE_CUSTOMER,
	REGISTER_DEVICE,
	AUTHENTICATE_CUSTOMER,
    UPDATE_CUSTOMER,
	RESET_PIN,
	GET_STORES,
	GET_TAGS,
	SEARCH_STORES,
	GET_PRODUCTS,
	GET_TAXONS,
	PLACE_ORDER,
	GET_PREVIOUS_ORDERS,
	GET_ORDER_BY_ID,
    GET_FAVOURITE_STORES,
    GET_FEATURED_STORES,
    GET_SUBURBS,
    GET_DELIVERY_PRICE;
}